server:
  port: 8888

spring:
  application:
    name: leyou-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5

zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到商品的微服务
